#!/usr/bin/python3
def raise_exception_msg(message=""):
    try:
        return (name_v)
    except NameError:
        print(message)
